<a href="https://colab.research.google.com/github/mohammedislam1776/ml-zoomcamp/blob/main/DTC_ML_ZoomCamp_HW_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DataTalks ML ZoomCamp Assignment 1

## Question 1: What version of Pandas did you install?



In [51]:
import pandas as pd
pd.__version__

'2.2.3'

## Question 2: How many records are in the dataset?



In [52]:
!wget https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv

--2026-09-16 04:20:18--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 635180 (620K) [text/plain]
Saving to: ‘car_fuel_efficiency_2026.csv.1’

car_fuel_efficiency 100%[===================>] 620.29K  --.-KB/s    in 0.03s   

2026-09-16 04:20:18 (19.8 MB/s) - ‘car_fuel_efficiency_2026.csv.1’ saved [635180/635180]



In [53]:
df = pd.read_csv('car_fuel_efficiency_2026.csv')
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0


In [54]:
df.describe()

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.000000,10000.00000,10000.000000,10000.000000,9123.000000,10000.000000,9736.000000,10000.000000
mean,1999.549500,3.50400,2268.807000,6.035200,254.446016,4286.754000,18.888044,29.997700
std,14.207925,0.95209,183.447355,0.542578,22.844613,266.212491,1.279543,2.930245
min,1975.000000,2.00000,1590.000000,4.000000,171.000000,3320.000000,14.000000,19.800000
25%,1987.000000,3.00000,2150.000000,6.000000,239.000000,4110.000000,18.000000,28.000000
50%,2000.000000,4.00000,2270.000000,6.000000,254.000000,4280.000000,18.900000,30.000000
75%,2012.000000,4.00000,2390.000000,6.000000,270.000000,4470.000000,19.700000,31.900000
max,2024.000000,5.00000,3110.000000,8.000000,334.000000,5460.000000,23.800000,41.200000


There are **10000** records in the dataset.

## Question 3: How many fuel types are presented in the dataset?



In [55]:
df['fuel_type'].unique()

array(['Gasoline', 'Diesel', 'Hybrid'], dtype=object)

There are **three** fuel types.

## Question 4: How many columns in the dataset have missing values?


In [56]:
df.isnull().sum()

,0
model_year,0
origin,0
fuel_type,0
drivetrain,0
num_doors,0
engine_displacement,0
num_cylinders,0
horsepower,877
vehicle_weight,0
acceleration,264


**2 columns** with null values

## Question 5: What's the maximum fuel efficiency of cars from Asia?



In [31]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

41.2

## Question 6: Median value of horsepower
1. Find the median value of the horsepower column in the dataset.
2. Next, calculate the most frequent value of the same horsepower column.
3. Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
4. Now, calculate the median value of horsepower once again.

Has it changed?



In [36]:
df['horsepower'].median()


254.0

In [37]:
df['horsepower'].mode()

,horsepower
0,252.0


In [34]:
df['horsepower'].fillna(df['horsepower'].mode())

,horsepower
0,243.0
1,272.0
2,267.0
3,258.0
4,304.0
...,...
9995,271.0
9996,244.0
9997,267.0
9998,270.0


In [35]:
df['horsepower'].median()

254.0

No, it did not change

## Question 7:
1. Select all the cars from Asia
2. Select only columns `vehicle_weight` and `model_year`
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it $X$.
5. Compute matrix-matrix multiplication between the *transpose of $X$* and $X$. To get the transpose, use X.T. Let's call the result $X^{T}X$.
6. Invert $X^{T}X$.
7. Create an array y with values `[1100, 1300, 800, 900, 1000, 1100, 1200]. `
8. Multiply the inverse of $X^{T}X$ with the transpose of $X$, and then multiply the result by $y$. Call the result $w$.
9. What's the sum of all the elements of the result?


In [38]:
df_asia = df[df['origin'] == 'Asia']
df_asia = df_asia[['vehicle_weight', 'model_year']]
df_asia = df_asia.head(7)
df_asia

,vehicle_weight,model_year
2,4240,1996
6,4310,1992
8,4230,1997
10,4420,1978
15,3950,2007
16,4750,2021
22,4450,2019


In [43]:
import numpy as np

In [45]:
xtx = np.dot(df_asia.T, df_asia)
xtx

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [46]:
xtxi = np.linalg.inv(xtx)
xtxi

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [47]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [48]:
w = np.dot(np.dot(xtxi, df_asia.T), y)
w

array([0.13644777, 0.2327492 ])

In [49]:
w.sum()

np.float64(0.36919696904925486)